import DevelopmentalBiologyMorphogenGradientsFoundationCanonicalLaneLean.MorphogenAdmissibleClass
import DevelopmentalBiologyMorphogenGradientsFoundationCanonicalLaneLean.BridgeLemmas
import DevelopmentalBiologyMorphogenGradientsFoundationCanonicalLaneLean.GateLemmas
import DevelopmentalBiologyMorphogenGradientsFoundationCanonicalLaneLean.FinalTheorem
import DevelopmentalBiologyMorphogenGradientsFoundationCanonicalLaneLean.ReactionDiffusionPDE
import DevelopmentalBiologyMorphogenGradientsFoundationCanonicalLaneLean.MorphogenTransport
import DevelopmentalBiologyMorphogenGradientsFoundationCanonicalLaneLean.GradientFormation

namespace HautevilleHouse
namespace DevelopmentalBiologyMorphogenGradientsFoundationCanonicalLaneLean

-- Package root

def packageDescription : String :=
  "Developmental Biology Morphogen Gradients Foundation Canonical Lane Lean"

end DevelopmentalBiologyMorphogenGradientsFoundationCanonicalLaneLean
end HautevilleHouse